In [1]:
%cd /content/drive/MyDrive/Association\ Rules
!ls

/content/drive/MyDrive/Association Rules
 AR-CatalogCrossSell.xls  ' Association_Rules.ipynb'

In [35]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules

In [32]:
data = pd.read_excel('AR-CatalogCrossSell.xls')
data

      Customer Number  ...  Jewelry Division
0               11569  ...                 0
1               13714  ...                 1
2               46391  ...                 1
3               67264  ...                 0
4               67363  ...                 0
...               ...  ...               ...
4993        337441034  ...                 0
4994        337498968  ...                 1
4995        337516678  ...                 1
4996        337528921  ...                 0
4997        337534044  ...                 0

[4998 rows x 10 columns]

In [33]:
data.drop(columns = 'Customer Number', inplace = True)
data

      Clothing Division  ...  Jewelry Division
0                     0  ...                 0
1                     0  ...                 1
2                     0  ...                 1
3                     0  ...                 0
4                     0  ...                 0
...                 ...  ...               ...
4993                  0  ...                 0
4994                  0  ...                 1
4995                  0  ...                 1
4996                  0  ...                 0
4997                  0  ...                 0

[4998 rows x 9 columns]

In [54]:
fp_result = fpgrowth.fpgrowth(data, min_support=0.4, use_colnames=True)
fp_result

    support                                           itemsets
0  1.000000                         (Health Products Division)
1  0.467387                    (Personal Electronics Division)
2  0.467387  (Health Products Division, Personal Electronic...

In [56]:
fp_result = fpgrowth.fpgrowth(data, min_support=0.3, use_colnames=True)
fp_result

    support                                           itemsets
0  1.000000                         (Health Products Division)
1  0.467387                    (Personal Electronics Division)
2  0.393557                              (Housewares Division)
3  0.356943                                 (Jewelry Division)
4  0.467387  (Health Products Division, Personal Electronic...
5  0.393557    (Health Products Division, Housewares Division)
6  0.356943       (Health Products Division, Jewelry Division)

In [57]:
fp_result = fpgrowth.fpgrowth(data, min_support=0.2, use_colnames=True)
fp_result

     support                                           itemsets
0   1.000000                         (Health Products Division)
1   0.467387                    (Personal Electronics Division)
2   0.393557                              (Housewares Division)
3   0.227491                            (Novelty Gift Division)
4   0.356943                                 (Jewelry Division)
5   0.272109                                  (Garden Division)
6   0.467387  (Health Products Division, Personal Electronic...
7   0.393557    (Health Products Division, Housewares Division)
8   0.235494  (Housewares Division, Personal Electronics Div...
9   0.235494  (Health Products Division, Housewares Division...
10  0.227491  (Health Products Division, Novelty Gift Division)
11  0.356943       (Health Products Division, Jewelry Division)
12  0.272109        (Health Products Division, Garden Division)

In [58]:
fp_result = fpgrowth.fpgrowth(data, min_support=0.1, use_colnames=True)
fp_result

     support                                           itemsets
0   1.000000                         (Health Products Division)
1   0.467387                    (Personal Electronics Division)
2   0.393557                              (Housewares Division)
3   0.227491                            (Novelty Gift Division)
4   0.134854                              (Automotive Division)
5   0.356943                                 (Jewelry Division)
6   0.272109                                  (Garden Division)
7   0.467387  (Health Products Division, Personal Electronic...
8   0.393557    (Health Products Division, Housewares Division)
9   0.235494  (Housewares Division, Personal Electronics Div...
10  0.235494  (Health Products Division, Housewares Division...
11  0.227491  (Health Products Division, Novelty Gift Division)
12  0.169068  (Personal Electronics Division, Novelty Gift D...
13  0.134854       (Housewares Division, Novelty Gift Division)
14  0.112245           (Novelty Gift Division, Garden Division)
15  0.107243          (Novelty Gift Division, Jewelry Division)
16  0.169068  (Health Products Division, Personal Electronic...
17  0.134854  (Health Products Division, Housewares Division...
18  0.107843  (Housewares Division, Personal Electronics Div...
19  0.107843  (Health Products Division, Housewares Division...
20  0.112245  (Health Products Division, Novelty Gift Divisi...
21  0.107243  (Health Products Division, Novelty Gift Divisi...
22  0.134854    (Health Products Division, Automotive Division)
23  0.356943       (Health Products Division, Jewelry Division)
24  0.197479  (Personal Electronics Division, Jewelry Division)
25  0.194878            (Housewares Division, Jewelry Division)
26  0.197479  (Health Products Division, Personal Electronic...
27  0.194878  (Health Products Division, Housewares Division...
28  0.132053  (Housewares Division, Jewelry Division, Person...
29  0.132053  (Health Products Division, Housewares Division...
30  0.272109        (Health Products Division, Garden Division)
31  0.163265   (Personal Electronics Division, Garden Division)
32  0.132853             (Housewares Division, Garden Division)
33  0.127251                (Jewelry Division, Garden Division)
34  0.163265  (Health Products Division, Personal Electronic...
35  0.132853  (Health Products Division, Housewares Division...
36  0.127251  (Health Products Division, Jewelry Division, G...

In [59]:
fp_association_rules = association_rules(fp_result, metric="confidence", min_threshold=0.7)
fp_association_rules

                                          antecedents  ... conviction
0                     (Personal Electronics Division)  ...        inf
1                               (Housewares Division)  ...        inf
2   (Housewares Division, Personal Electronics Div...  ...        inf
3                             (Novelty Gift Division)  ...        inf
4                             (Novelty Gift Division)  ...   2.073908
5   (Health Products Division, Novelty Gift Division)  ...   2.073908
6   (Personal Electronics Division, Novelty Gift D...  ...        inf
7                             (Novelty Gift Division)  ...   2.073908
8        (Housewares Division, Novelty Gift Division)  ...        inf
9        (Housewares Division, Novelty Gift Division)  ...   2.659120
10  (Health Products Division, Housewares Division...  ...   2.659120
11  (Housewares Division, Personal Electronics Div...  ...        inf
12       (Housewares Division, Novelty Gift Division)  ...   2.659120
13           (Novelty Gift Division, Garden Division)  ...        inf
14          (Novelty Gift Division, Jewelry Division)  ...        inf
15                              (Automotive Division)  ...        inf
16                                 (Jewelry Division)  ...        inf
17  (Personal Electronics Division, Jewelry Division)  ...        inf
18            (Housewares Division, Jewelry Division)  ...        inf
19  (Housewares Division, Jewelry Division, Person...  ...        inf
20                                  (Garden Division)  ...        inf
21   (Personal Electronics Division, Garden Division)  ...        inf
22             (Housewares Division, Garden Division)  ...        inf
23                (Jewelry Division, Garden Division)  ...        inf

[24 rows x 9 columns]

In [60]:
fp_result.to_csv('fp_result.csv')
fp_association_rules.to_csv('fp_association_rules.csv')